# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('Elementary', 'Elementary School'), ('Middle', 'Middle School'), ('High', 'High School'), ('Vocational', 'Vocational School')], default='Elementary', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Person')),
                ('school', models.CharField(max_length=20)),
            ],
            bases=('login.person',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='login.Person')),
                ('parent_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            bases=('login.person',),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_of_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Parent'),
        ),
    ]
