# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandIds',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
